// Veglia localisation: 20 languages in one file, no .strings, no Xcode.
// The language comes from the system (first preferred language) unless the user picked
// one in the menu; anything not listed here falls back to English.
// Placeholders: %@ — app names, %d — minutes.

import Foundation

enum L {
    // Keys in menu order.
    enum Key: String, CaseIterable {
        case watchApps        // "Watch apps" item
        case watchHint        // hint inside the apps submenu
        case alwaysOn         // "Stay awake always"
        case keepDisplay      // "Keep the display on"
        case launchAtLogin    // "Launch at login"
        case quit             // "Quit Veglia"
        case idle             // status line when nothing is running
        case manual           // status line in manual mode
        case runningOne       // "%@ is running — the Mac stays awake"
        case runningMany      // "%@ are running — the Mac stays awake"
        case minutes          // "%d min"
        case closed           // "(closed)" next to ticked apps that are not running
        case tipOn            // icon tooltip: watching
        case tipOff           // icon tooltip: resting
        case language         // "Language" item
        case systemLanguage   // "Same as system" in the language submenu
        case lidMode          // "Work with the lid closed"
        case lidWarnTitle     // warning title
        case lidWarnText      // warning text: heat, battery, password
        case enable           // "Turn on" button
        case cancel           // "Cancel" button
        case lidFailed        // helper install failed
        case watchAgents      // "Watch agents"
        case agentsHint       // hint inside the agents submenu
        case terminals        // "While a terminal is open"
        case terminalName     // "Terminal" in the status line
        case support          // "Support Veglia" — opens the Ko-fi page
    }

    /// Donation page opened by the "Support" menu item.
    static let supportURL = "https://ko-fi.com/rosabosa"

    /// Languages for the submenu: code and native name, in display order.
    static let names: [(code: String, native: String)] = [
        ("en", "English"), ("ru", "Русский"), ("it", "Italiano"), ("es", "Español"),
        ("pt", "Português"), ("fr", "Français"), ("de", "Deutsch"), ("nl", "Nederlands"),
        ("pl", "Polski"), ("uk", "Українська"), ("tr", "Türkçe"), ("ar", "العربية"),
        ("hi", "हिन्दी"), ("zh-Hans", "简体中文"), ("zh-Hant", "繁體中文"), ("ja", "日本語"),
        ("ko", "한국어"), ("id", "Bahasa Indonesia"), ("vi", "Tiếng Việt"), ("th", "ไทย"),
    ]

    /// Language picked in the menu; nil means same as system. Stored in UserDefaults.
    static var override: String? {
        get { let v = UserDefaults.standard.string(forKey: "language"); return (v ?? "").isEmpty ? nil : v }
        set { UserDefaults.standard.set(newValue ?? "", forKey: "language") }
    }

    static func t(_ key: Key) -> String {
        tables[lang]?[key] ?? tables["en"]![key]!
    }

    /// Current language: the picked one, otherwise the system one.
    static var lang: String { override.flatMap { tables[$0] != nil ? $0 : nil } ?? systemLang }

    /// System language code mapped to a table key (zh-Hans and zh-Hant are distinguished).
    static let systemLang: String = {
        let pref = Locale.preferredLanguages.first ?? "en"
        if pref.hasPrefix("zh") {
            return (pref.contains("Hant") || pref.contains("TW") || pref.contains("HK")) ? "zh-Hant" : "zh-Hans"
        }
        let code = String(pref.split(separator: "-").first ?? "en")
        return tables[code] != nil ? code : "en"
    }()

    static let tables: [String: [Key: String]] = [
        "en": [
            .watchApps: "Watch apps",
            .watchHint: "While a checked app is running, the Mac stays awake",
            .alwaysOn: "Stay awake always",
            .keepDisplay: "Keep the display on",
            .launchAtLogin: "Launch at login",
            .quit: "Quit Veglia",
            .idle: "Nothing running — the Mac may sleep",
            .manual: "Mac stays awake (turned on manually)",
            .runningOne: "%@ is running — the Mac stays awake",
            .runningMany: "%@ are running — the Mac stays awake",
            .minutes: "%d min",
            .closed: "(closed)",
            .tipOn: "Veglia: the Mac won't sleep",
            .tipOff: "Veglia: resting",
            .language: "Language",
            .systemLanguage: "Same as system",
            .lidMode: "Work with the lid closed",
            .lidWarnTitle: "The Mac will keep running with the lid closed",
            .lidWarnText: "While a Claude Code session or a watched app is running, the closed Mac will not sleep.\n\nA closed laptop that keeps working gets warm: do not put it in a bag or under a pillow. The battery drains as if the lid were open.\n\nTurning this on installs a small system helper and asks for an administrator password once.",
            .enable: "Turn on",
            .cancel: "Cancel",
            .lidFailed: "Could not install the helper. The mode stays off.",
            .watchAgents: "Watch agents",
            .agentsHint: "Agents are detected automatically; untick any you don't want",
            .terminals: "While a terminal is open",
            .terminalName: "Terminal",
            .support: "Support Veglia ♥",
        ],
        "ru": [
            .watchApps: "Следить за приложениями",
            .watchHint: "Пока отмеченное приложение запущено, Мак не спит",
            .alwaysOn: "Держать бодрым всегда",
            .keepDisplay: "Не гасить экран",
            .launchAtLogin: "Запускать при входе в систему",
            .quit: "Выйти из Veglia",
            .idle: "Ничего не работает — Мак может спать",
            .manual: "Мак не спит (включено вручную)",
            .runningOne: "%@ работает — Мак не спит",
            .runningMany: "%@ работают — Мак не спит",
            .minutes: "%d мин",
            .closed: "(закрыто)",
            .tipOn: "Veglia: Мак не заснёт",
            .tipOff: "Veglia: отдыхает",
            .language: "Язык",
            .systemLanguage: "Как в системе",
            .lidMode: "Работать с закрытой крышкой",
            .lidWarnTitle: "Мак будет работать с закрытой крышкой",
            .lidWarnText: "Пока идёт сессия Claude Code или работает отмеченное приложение, закрытый Мак не заснёт.\n\nЗакрытый работающий ноутбук греется: не кладите его в сумку и под подушку. Батарея расходуется как при открытой крышке.\n\nПри включении ставится маленький системный помощник и один раз спрашивается пароль администратора.",
            .enable: "Включить",
            .cancel: "Отмена",
            .lidFailed: "Не удалось установить помощник. Режим остался выключенным.",
            .watchAgents: "Следить за агентами",
            .agentsHint: "Агенты определяются сами; лишних можно снять галочкой",
            .terminals: "Пока открыт терминал",
            .terminalName: "Терминал",
            .support: "Поддержать Veglia ♥",
        ],
        "it": [
            .watchApps: "Sorveglia app",
            .watchHint: "Finché un'app spuntata è aperta, il Mac resta sveglio",
            .alwaysOn: "Resta sempre sveglio",
            .keepDisplay: "Tieni acceso lo schermo",
            .launchAtLogin: "Apri al login",
            .quit: "Esci da Veglia",
            .idle: "Niente in esecuzione — il Mac può dormire",
            .manual: "Il Mac resta sveglio (attivato a mano)",
            .runningOne: "%@ è in esecuzione — il Mac resta sveglio",
            .runningMany: "%@ sono in esecuzione — il Mac resta sveglio",
            .minutes: "%d min",
            .closed: "(chiusa)",
            .tipOn: "Veglia: il Mac non dormirà",
            .tipOff: "Veglia: a riposo",
            .language: "Lingua",
            .systemLanguage: "Come nel sistema",
            .lidMode: "Lavora a coperchio chiuso",
            .lidWarnTitle: "Il Mac continuerà a lavorare a coperchio chiuso",
            .lidWarnText: "Finché una sessione di Claude Code o un'app sorvegliata è attiva, il Mac chiuso non dormirà.\n\nUn portatile chiuso che lavora si scalda: non metterlo in borsa o sotto un cuscino. La batteria si consuma come a coperchio aperto.\n\nL'attivazione installa un piccolo helper di sistema e chiede una volta la password di amministratore.",
            .enable: "Attiva",
            .cancel: "Annulla",
            .lidFailed: "Impossibile installare l'helper. La modalità resta disattivata.",
            .watchAgents: "Sorveglia agenti",
            .agentsHint: "Gli agenti vengono rilevati da soli; togli la spunta a quelli che non vuoi",
            .terminals: "Finché un terminale è aperto",
            .terminalName: "Terminale",
            .support: "Sostieni Veglia ♥",
        ],
        "es": [
            .watchApps: "Vigilar apps",
            .watchHint: "Mientras una app marcada esté abierta, el Mac no se dormirá",
            .alwaysOn: "Mantener despierto siempre",
            .keepDisplay: "Mantener la pantalla encendida",
            .launchAtLogin: "Abrir al iniciar sesión",
            .quit: "Salir de Veglia",
            .idle: "Nada en ejecución — el Mac puede dormir",
            .manual: "El Mac sigue despierto (activado a mano)",
            .runningOne: "%@ está en ejecución — el Mac sigue despierto",
            .runningMany: "%@ están en ejecución — el Mac sigue despierto",
            .minutes: "%d min",
            .closed: "(cerrada)",
            .tipOn: "Veglia: el Mac no se dormirá",
            .tipOff: "Veglia: en reposo",
            .language: "Idioma",
            .systemLanguage: "Igual que el sistema",
            .lidMode: "Trabajar con la tapa cerrada",
            .lidWarnTitle: "El Mac seguirá funcionando con la tapa cerrada",
            .lidWarnText: "Mientras haya una sesión de Claude Code o una app vigilada en ejecución, el Mac cerrado no se dormirá.\n\nUn portátil cerrado que sigue trabajando se calienta: no lo metas en una bolsa ni bajo una almohada. La batería se gasta como con la tapa abierta.\n\nAl activarlo se instala un pequeño ayudante del sistema y se pide una vez la contraseña de administrador.",
            .enable: "Activar",
            .cancel: "Cancelar",
            .lidFailed: "No se pudo instalar el ayudante. El modo sigue desactivado.",
            .watchAgents: "Vigilar agentes",
            .agentsHint: "Los agentes se detectan solos; desmarca los que no quieras",
            .terminals: "Mientras haya un terminal abierto",
            .terminalName: "Terminal",
            .support: "Apoyar Veglia ♥",
        ],
        "pt": [
            .watchApps: "Vigiar apps",
            .watchHint: "Enquanto um app marcado estiver aberto, o Mac fica acordado",
            .alwaysOn: "Manter sempre acordado",
            .keepDisplay: "Manter a tela ligada",
            .launchAtLogin: "Abrir ao iniciar sessão",
            .quit: "Sair do Veglia",
            .idle: "Nada em execução — o Mac pode dormir",
            .manual: "O Mac fica acordado (ativado manualmente)",
            .runningOne: "%@ está em execução — o Mac fica acordado",
            .runningMany: "%@ estão em execução — o Mac fica acordado",
            .minutes: "%d min",
            .closed: "(fechado)",
            .tipOn: "Veglia: o Mac não vai dormir",
            .tipOff: "Veglia: em repouso",
            .language: "Idioma",
            .systemLanguage: "Igual ao sistema",
            .lidMode: "Trabalhar com a tampa fechada",
            .lidWarnTitle: "O Mac continuará a trabalhar com a tampa fechada",
            .lidWarnText: "Enquanto uma sessão do Claude Code ou um app vigiado estiver em execução, o Mac fechado não dormirá.\n\nUm portátil fechado a trabalhar aquece: não o coloque numa mala nem debaixo de uma almofada. A bateria gasta-se como com a tampa aberta.\n\nAo ativar, instala-se um pequeno auxiliar do sistema e a senha de administrador é pedida uma vez.",
            .enable: "Ativar",
            .cancel: "Cancelar",
            .lidFailed: "Não foi possível instalar o auxiliar. O modo continua desligado.",
            .watchAgents: "Vigiar agentes",
            .agentsHint: "Os agentes são detectados sozinhos; desmarque os que não quiser",
            .terminals: "Enquanto um terminal estiver aberto",
            .terminalName: "Terminal",
            .support: "Apoiar o Veglia ♥",
        ],
        "fr": [
            .watchApps: "Surveiller des apps",
            .watchHint: "Tant qu'une app cochée est ouverte, le Mac reste éveillé",
            .alwaysOn: "Rester toujours éveillé",
            .keepDisplay: "Garder l'écran allumé",
            .launchAtLogin: "Ouvrir à la connexion",
            .quit: "Quitter Veglia",
            .idle: "Rien en cours — le Mac peut dormir",
            .manual: "Le Mac reste éveillé (activé manuellement)",
            .runningOne: "%@ est en cours — le Mac reste éveillé",
            .runningMany: "%@ sont en cours — le Mac reste éveillé",
            .minutes: "%d min",
            .closed: "(fermée)",
            .tipOn: "Veglia : le Mac ne dormira pas",
            .tipOff: "Veglia : au repos",
            .language: "Langue",
            .systemLanguage: "Comme le système",
            .lidMode: "Travailler capot fermé",
            .lidWarnTitle: "Le Mac continuera à travailler capot fermé",
            .lidWarnText: "Tant qu'une session Claude Code ou une app surveillée tourne, le Mac fermé ne dormira pas.\n\nUn portable fermé qui travaille chauffe : ne le mettez pas dans un sac ni sous un oreiller. La batterie se vide comme capot ouvert.\n\nL'activation installe un petit assistant système et demande une fois le mot de passe administrateur.",
            .enable: "Activer",
            .cancel: "Annuler",
            .lidFailed: "Impossible d'installer l'assistant. Le mode reste désactivé.",
            .watchAgents: "Surveiller les agents",
            .agentsHint: "Les agents sont détectés automatiquement ; décochez ceux que vous ne voulez pas",
            .terminals: "Tant qu'un terminal est ouvert",
            .terminalName: "Terminal",
            .support: "Soutenir Veglia ♥",
        ],
        "de": [
            .watchApps: "Apps überwachen",
            .watchHint: "Solange eine markierte App läuft, bleibt der Mac wach",
            .alwaysOn: "Immer wach bleiben",
            .keepDisplay: "Bildschirm anlassen",
            .launchAtLogin: "Bei der Anmeldung starten",
            .quit: "Veglia beenden",
            .idle: "Nichts läuft — der Mac darf schlafen",
            .manual: "Der Mac bleibt wach (manuell eingeschaltet)",
            .runningOne: "%@ läuft — der Mac bleibt wach",
            .runningMany: "%@ laufen — der Mac bleibt wach",
            .minutes: "%d Min.",
            .closed: "(geschlossen)",
            .tipOn: "Veglia: Der Mac schläft nicht ein",
            .tipOff: "Veglia: ruht",
            .language: "Sprache",
            .systemLanguage: "Wie das System",
            .lidMode: "Mit geschlossenem Deckel arbeiten",
            .lidWarnTitle: "Der Mac arbeitet mit geschlossenem Deckel weiter",
            .lidWarnText: "Solange eine Claude-Code-Sitzung oder eine überwachte App läuft, schläft der geschlossene Mac nicht ein.\n\nEin geschlossenes, arbeitendes Notebook wird warm: nicht in die Tasche oder unter ein Kissen legen. Der Akku entlädt sich wie bei offenem Deckel.\n\nBeim Einschalten wird ein kleiner Systemhelfer installiert und einmal das Administratorpasswort abgefragt.",
            .enable: "Einschalten",
            .cancel: "Abbrechen",
            .lidFailed: "Der Helfer konnte nicht installiert werden. Der Modus bleibt aus.",
            .watchAgents: "Agenten überwachen",
            .agentsHint: "Agenten werden automatisch erkannt; unerwünschte abwählen",
            .terminals: "Solange ein Terminal offen ist",
            .terminalName: "Terminal",
            .support: "Veglia unterstützen ♥",
        ],
        "nl": [
            .watchApps: "Apps bewaken",
            .watchHint: "Zolang een aangevinkte app draait, blijft de Mac wakker",
            .alwaysOn: "Altijd wakker blijven",
            .keepDisplay: "Scherm aan laten",
            .launchAtLogin: "Openen bij inloggen",
            .quit: "Veglia afsluiten",
            .idle: "Niets actief — de Mac mag slapen",
            .manual: "De Mac blijft wakker (handmatig ingeschakeld)",
            .runningOne: "%@ draait — de Mac blijft wakker",
            .runningMany: "%@ draaien — de Mac blijft wakker",
            .minutes: "%d min",
            .closed: "(gesloten)",
            .tipOn: "Veglia: de Mac valt niet in slaap",
            .tipOff: "Veglia: rust",
            .language: "Taal",
            .systemLanguage: "Zoals het systeem",
            .lidMode: "Werken met gesloten deksel",
            .lidWarnTitle: "De Mac blijft werken met gesloten deksel",
            .lidWarnText: "Zolang een Claude Code-sessie of een bewaakte app draait, valt de gesloten Mac niet in slaap.\n\nEen gesloten laptop die doorwerkt wordt warm: leg hem niet in een tas of onder een kussen. De batterij loopt leeg alsof het deksel open is.\n\nBij inschakelen wordt een kleine systeemhelper geïnstalleerd en eenmalig om het beheerderswachtwoord gevraagd.",
            .enable: "Inschakelen",
            .cancel: "Annuleer",
            .lidFailed: "De helper kon niet worden geïnstalleerd. De modus blijft uit.",
            .watchAgents: "Agents bewaken",
            .agentsHint: "Agents worden automatisch herkend; vink uit wat je niet wilt",
            .terminals: "Zolang een terminal open is",
            .terminalName: "Terminal",
            .support: "Steun Veglia ♥",
        ],
        "pl": [
            .watchApps: "Pilnuj aplikacji",
            .watchHint: "Dopóki zaznaczona aplikacja działa, Mac nie zaśnie",
            .alwaysOn: "Zawsze nie usypiaj",
            .keepDisplay: "Nie wygaszaj ekranu",
            .launchAtLogin: "Uruchamiaj przy logowaniu",
            .quit: "Zakończ Veglia",
            .idle: "Nic nie działa — Mac może spać",
            .manual: "Mac nie śpi (włączone ręcznie)",
            .runningOne: "%@ działa — Mac nie śpi",
            .runningMany: "%@ działają — Mac nie śpi",
            .minutes: "%d min",
            .closed: "(zamknięta)",
            .tipOn: "Veglia: Mac nie zaśnie",
            .tipOff: "Veglia: odpoczywa",
            .language: "Język",
            .systemLanguage: "Jak w systemie",
            .lidMode: "Pracuj z zamkniętą pokrywą",
            .lidWarnTitle: "Mac będzie pracować z zamkniętą pokrywą",
            .lidWarnText: "Dopóki trwa sesja Claude Code lub działa pilnowana aplikacja, zamknięty Mac nie zaśnie.\n\nZamknięty pracujący laptop się nagrzewa: nie wkładaj go do torby ani pod poduszkę. Bateria zużywa się jak przy otwartej pokrywie.\n\nWłączenie instaluje mały pomocnik systemowy i raz pyta o hasło administratora.",
            .enable: "Włącz",
            .cancel: "Anuluj",
            .lidFailed: "Nie udało się zainstalować pomocnika. Tryb pozostaje wyłączony.",
            .watchAgents: "Pilnuj agentów",
            .agentsHint: "Agenci są wykrywani automatycznie; odznacz niepotrzebnych",
            .terminals: "Dopóki otwarty jest terminal",
            .terminalName: "Terminal",
            .support: "Wesprzyj Veglia ♥",
        ],
        "uk": [
            .watchApps: "Стежити за програмами",
            .watchHint: "Поки позначена програма запущена, Mac не спить",
            .alwaysOn: "Не засинати ніколи",
            .keepDisplay: "Не вимикати екран",
            .launchAtLogin: "Запускати під час входу",
            .quit: "Вийти з Veglia",
            .idle: "Нічого не працює — Mac може спати",
            .manual: "Mac не спить (увімкнено вручну)",
            .runningOne: "%@ працює — Mac не спить",
            .runningMany: "%@ працюють — Mac не спить",
            .minutes: "%d хв",
            .closed: "(закрито)",
            .tipOn: "Veglia: Mac не засне",
            .tipOff: "Veglia: відпочиває",
            .language: "Мова",
            .systemLanguage: "Як у системі",
            .lidMode: "Працювати із закритою кришкою",
            .lidWarnTitle: "Mac працюватиме із закритою кришкою",
            .lidWarnText: "Поки триває сесія Claude Code або працює позначена програма, закритий Mac не засне.\n\nЗакритий працюючий ноутбук гріється: не кладіть його в сумку чи під подушку. Батарея витрачається як із відкритою кришкою.\n\nПід час увімкнення ставиться маленький системний помічник і один раз запитується пароль адміністратора.",
            .enable: "Увімкнути",
            .cancel: "Скасувати",
            .lidFailed: "Не вдалося встановити помічник. Режим залишився вимкненим.",
            .watchAgents: "Стежити за агентами",
            .agentsHint: "Агенти визначаються самі; зайвих можна зняти",
            .terminals: "Поки відкритий термінал",
            .terminalName: "Термінал",
            .support: "Підтримати Veglia ♥",
        ],
        "tr": [
            .watchApps: "Uygulamaları izle",
            .watchHint: "İşaretli bir uygulama açıkken Mac uyanık kalır",
            .alwaysOn: "Her zaman uyanık kal",
            .keepDisplay: "Ekranı açık tut",
            .launchAtLogin: "Oturum açılınca başlat",
            .quit: "Veglia'dan çık",
            .idle: "Çalışan yok — Mac uyuyabilir",
            .manual: "Mac uyanık (elle açıldı)",
            .runningOne: "%@ çalışıyor — Mac uyanık",
            .runningMany: "%@ çalışıyor — Mac uyanık",
            .minutes: "%d dk",
            .closed: "(kapalı)",
            .tipOn: "Veglia: Mac uyumayacak",
            .tipOff: "Veglia: dinleniyor",
            .language: "Dil",
            .systemLanguage: "Sistemle aynı",
            .lidMode: "Kapak kapalıyken çalış",
            .lidWarnTitle: "Mac kapak kapalıyken çalışmaya devam edecek",
            .lidWarnText: "Bir Claude Code oturumu veya izlenen bir uygulama çalıştığı sürece kapalı Mac uyumaz.\n\nKapalıyken çalışan dizüstü ısınır: çantaya veya yastık altına koymayın. Pil, kapak açıkmış gibi tükenir.\n\nAçıldığında küçük bir sistem yardımcısı kurulur ve bir kez yönetici parolası istenir.",
            .enable: "Aç",
            .cancel: "Vazgeç",
            .lidFailed: "Yardımcı kurulamadı. Mod kapalı kaldı.",
            .watchAgents: "Ajanları izle",
            .agentsHint: "Ajanlar otomatik algılanır; istemediklerinizin işaretini kaldırın",
            .terminals: "Bir terminal açıkken",
            .terminalName: "Terminal",
            .support: "Veglia'yı destekle ♥",
        ],
        "ar": [
            .watchApps: "مراقبة التطبيقات",
            .watchHint: "ما دام تطبيق محدد يعمل، يبقى الماك مستيقظًا",
            .alwaysOn: "البقاء مستيقظًا دائمًا",
            .keepDisplay: "إبقاء الشاشة مضاءة",
            .launchAtLogin: "التشغيل عند تسجيل الدخول",
            .quit: "إنهاء Veglia",
            .idle: "لا شيء يعمل — يمكن للماك أن ينام",
            .manual: "الماك مستيقظ (مفعّل يدويًا)",
            .runningOne: "%@ يعمل — الماك مستيقظ",
            .runningMany: "%@ تعمل — الماك مستيقظ",
            .minutes: "%d د",
            .closed: "(مغلق)",
            .tipOn: "Veglia: لن ينام الماك",
            .tipOff: "Veglia: في راحة",
            .language: "اللغة",
            .systemLanguage: "مثل النظام",
            .lidMode: "العمل والغطاء مغلق",
            .lidWarnTitle: "سيواصل الماك العمل والغطاء مغلق",
            .lidWarnText: "ما دامت جلسة Claude Code أو تطبيق مراقَب يعمل، لن ينام الماك المغلق.\n\nالحاسوب المحمول المغلق الذي يعمل يسخن: لا تضعه في حقيبة أو تحت وسادة. تُستهلك البطارية كما لو كان الغطاء مفتوحًا.\n\nعند التفعيل يُثبَّت مساعد نظام صغير وتُطلب كلمة مرور المسؤول مرة واحدة.",
            .enable: "تفعيل",
            .cancel: "إلغاء",
            .lidFailed: "تعذّر تثبيت المساعد. يبقى الوضع متوقفًا.",
            .watchAgents: "مراقبة الوكلاء",
            .agentsHint: "يتم اكتشاف الوكلاء تلقائيًا؛ ألغِ تحديد ما لا تريده",
            .terminals: "ما دامت الطرفية مفتوحة",
            .terminalName: "الطرفية",
            .support: "ادعم Veglia ♥",
        ],
        "hi": [
            .watchApps: "ऐप्स पर नज़र रखें",
            .watchHint: "जब तक चुना हुआ ऐप चल रहा है, Mac जागता रहेगा",
            .alwaysOn: "हमेशा जागते रहें",
            .keepDisplay: "स्क्रीन चालू रखें",
            .launchAtLogin: "लॉगिन पर शुरू करें",
            .quit: "Veglia बंद करें",
            .idle: "कुछ नहीं चल रहा — Mac सो सकता है",
            .manual: "Mac जाग रहा है (हाथ से चालू)",
            .runningOne: "%@ चल रहा है — Mac जाग रहा है",
            .runningMany: "%@ चल रहे हैं — Mac जाग रहा है",
            .minutes: "%d मिनट",
            .closed: "(बंद)",
            .tipOn: "Veglia: Mac नहीं सोएगा",
            .tipOff: "Veglia: आराम में",
            .language: "भाषा",
            .systemLanguage: "सिस्टम जैसी",
            .lidMode: "ढक्कन बंद रखकर काम करें",
            .lidWarnTitle: "ढक्कन बंद होने पर भी Mac चलता रहेगा",
            .lidWarnText: "जब तक Claude Code सत्र या चुना हुआ ऐप चल रहा है, बंद Mac नहीं सोएगा।\n\nबंद होकर चलता लैपटॉप गर्म होता है: इसे बैग में या तकिये के नीचे न रखें। बैटरी वैसे ही खर्च होगी जैसे ढक्कन खुला हो।\n\nचालू करने पर एक छोटा सिस्टम सहायक इंस्टॉल होता है और एक बार व्यवस्थापक पासवर्ड पूछा जाता है।",
            .enable: "चालू करें",
            .cancel: "रद्द करें",
            .lidFailed: "सहायक इंस्टॉल नहीं हो सका। मोड बंद ही रहा।",
            .watchAgents: "एजेंट्स पर नज़र रखें",
            .agentsHint: "एजेंट अपने आप पहचाने जाते हैं; जो न चाहिए उन्हें अनचेक करें",
            .terminals: "जब तक टर्मिनल खुला है",
            .terminalName: "टर्मिनल",
            .support: "Veglia का समर्थन करें ♥",
        ],
        "zh-Hans": [
            .watchApps: "看守应用",
            .watchHint: "只要勾选的应用在运行，Mac 就不会睡眠",
            .alwaysOn: "始终保持唤醒",
            .keepDisplay: "保持屏幕常亮",
            .launchAtLogin: "登录时启动",
            .quit: "退出 Veglia",
            .idle: "没有运行的任务 — Mac 可以睡眠",
            .manual: "Mac 保持唤醒（手动开启）",
            .runningOne: "%@ 正在运行 — Mac 保持唤醒",
            .runningMany: "%@ 正在运行 — Mac 保持唤醒",
            .minutes: "%d 分钟",
            .closed: "（已关闭）",
            .tipOn: "Veglia：Mac 不会睡眠",
            .tipOff: "Veglia：休息中",
            .language: "语言",
            .systemLanguage: "跟随系统",
            .lidMode: "合盖继续工作",
            .lidWarnTitle: "合上盖子后 Mac 仍会继续运行",
            .lidWarnText: "只要 Claude Code 会话或被看守的应用在运行，合盖的 Mac 就不会睡眠。\n\n合盖工作的笔记本会发热：不要放进包里或压在枕头下。电池消耗与开盖时相同。\n\n开启时会安装一个小型系统助手，并询问一次管理员密码。",
            .enable: "开启",
            .cancel: "取消",
            .lidFailed: "无法安装助手。该模式保持关闭。",
            .watchAgents: "看守代理",
            .agentsHint: "代理会自动识别；不需要的可以取消勾选",
            .terminals: "只要终端打开着",
            .terminalName: "终端",
            .support: "支持 Veglia ♥",
        ],
        "zh-Hant": [
            .watchApps: "看守應用程式",
            .watchHint: "只要勾選的應用程式在執行，Mac 就不會睡眠",
            .alwaysOn: "始終保持喚醒",
            .keepDisplay: "保持螢幕常亮",
            .launchAtLogin: "登入時啟動",
            .quit: "結束 Veglia",
            .idle: "沒有執行中的任務 — Mac 可以睡眠",
            .manual: "Mac 保持喚醒（手動開啟）",
            .runningOne: "%@ 執行中 — Mac 保持喚醒",
            .runningMany: "%@ 執行中 — Mac 保持喚醒",
            .minutes: "%d 分鐘",
            .closed: "（已關閉）",
            .tipOn: "Veglia：Mac 不會睡眠",
            .tipOff: "Veglia：休息中",
            .language: "語言",
            .systemLanguage: "跟隨系統",
            .lidMode: "合蓋繼續工作",
            .lidWarnTitle: "合上蓋子後 Mac 仍會繼續執行",
            .lidWarnText: "只要 Claude Code 工作階段或被看守的應用程式在執行，合蓋的 Mac 就不會睡眠。\n\n合蓋工作的筆電會發熱：不要放進包包或壓在枕頭下。電池消耗與開蓋時相同。\n\n開啟時會安裝一個小型系統輔助程式，並詢問一次管理員密碼。",
            .enable: "開啟",
            .cancel: "取消",
            .lidFailed: "無法安裝輔助程式。此模式保持關閉。",
            .watchAgents: "看守代理",
            .agentsHint: "代理會自動辨識；不需要的可以取消勾選",
            .terminals: "只要終端機開著",
            .terminalName: "終端機",
            .support: "支持 Veglia ♥",
        ],
        "ja": [
            .watchApps: "アプリを見守る",
            .watchHint: "チェックしたアプリが動いている間、Mac はスリープしません",
            .alwaysOn: "常にスリープさせない",
            .keepDisplay: "画面を消さない",
            .launchAtLogin: "ログイン時に起動",
            .quit: "Veglia を終了",
            .idle: "動作中のものはありません — Mac はスリープできます",
            .manual: "Mac はスリープしません（手動でオン）",
            .runningOne: "%@ が動作中 — Mac はスリープしません",
            .runningMany: "%@ が動作中 — Mac はスリープしません",
            .minutes: "%d 分",
            .closed: "（終了済み）",
            .tipOn: "Veglia：Mac はスリープしません",
            .tipOff: "Veglia：休止中",
            .language: "言語",
            .systemLanguage: "システムに合わせる",
            .lidMode: "ふたを閉じても動作",
            .lidWarnTitle: "ふたを閉じても Mac は動作し続けます",
            .lidWarnText: "Claude Code のセッションや見守り中のアプリが動いている間、閉じた Mac はスリープしません。\n\n閉じたまま動作するノートは熱を持ちます。バッグや枕の下に入れないでください。バッテリーはふたを開けているときと同じように減ります。\n\nオンにすると小さなシステムヘルパーをインストールし、管理者パスワードを一度だけ求めます。",
            .enable: "オンにする",
            .cancel: "キャンセル",
            .lidFailed: "ヘルパーをインストールできませんでした。モードはオフのままです。",
            .watchAgents: "エージェントを見守る",
            .agentsHint: "エージェントは自動で検出されます。不要なものはチェックを外してください",
            .terminals: "ターミナルが開いている間",
            .terminalName: "ターミナル",
            .support: "Veglia を応援する ♥",
        ],
        "ko": [
            .watchApps: "앱 지켜보기",
            .watchHint: "체크한 앱이 실행 중인 동안 Mac은 잠들지 않습니다",
            .alwaysOn: "항상 깨어 있기",
            .keepDisplay: "화면 켜 두기",
            .launchAtLogin: "로그인 시 실행",
            .quit: "Veglia 종료",
            .idle: "실행 중인 것이 없음 — Mac이 잠들 수 있습니다",
            .manual: "Mac이 깨어 있음 (수동으로 켬)",
            .runningOne: "%@ 실행 중 — Mac이 깨어 있음",
            .runningMany: "%@ 실행 중 — Mac이 깨어 있음",
            .minutes: "%d분",
            .closed: "(닫힘)",
            .tipOn: "Veglia: Mac이 잠들지 않습니다",
            .tipOff: "Veglia: 쉬는 중",
            .language: "언어",
            .systemLanguage: "시스템과 동일",
            .lidMode: "덮개를 닫아도 작동",
            .lidWarnTitle: "덮개를 닫아도 Mac이 계속 작동합니다",
            .lidWarnText: "Claude Code 세션이나 지켜보는 앱이 실행 중인 동안 닫힌 Mac은 잠들지 않습니다.\n\n닫힌 채 작동하는 노트북은 뜨거워집니다. 가방이나 베개 밑에 두지 마세요. 배터리는 덮개를 연 것처럼 소모됩니다.\n\n켜면 작은 시스템 도우미가 설치되고 관리자 암호를 한 번 묻습니다.",
            .enable: "켜기",
            .cancel: "취소",
            .lidFailed: "도우미를 설치할 수 없습니다. 모드는 꺼진 상태로 유지됩니다.",
            .watchAgents: "에이전트 지켜보기",
            .agentsHint: "에이전트는 자동으로 감지됩니다. 원하지 않는 것은 체크를 해제하세요",
            .terminals: "터미널이 열려 있는 동안",
            .terminalName: "터미널",
            .support: "Veglia 후원하기 ♥",
        ],
        "id": [
            .watchApps: "Awasi aplikasi",
            .watchHint: "Selama aplikasi yang dicentang berjalan, Mac tetap terjaga",
            .alwaysOn: "Selalu tetap terjaga",
            .keepDisplay: "Biarkan layar menyala",
            .launchAtLogin: "Jalankan saat login",
            .quit: "Keluar dari Veglia",
            .idle: "Tidak ada yang berjalan — Mac boleh tidur",
            .manual: "Mac tetap terjaga (dinyalakan manual)",
            .runningOne: "%@ sedang berjalan — Mac tetap terjaga",
            .runningMany: "%@ sedang berjalan — Mac tetap terjaga",
            .minutes: "%d mnt",
            .closed: "(tertutup)",
            .tipOn: "Veglia: Mac tidak akan tidur",
            .tipOff: "Veglia: beristirahat",
            .language: "Bahasa",
            .systemLanguage: "Ikuti sistem",
            .lidMode: "Bekerja dengan penutup tertutup",
            .lidWarnTitle: "Mac akan terus bekerja dengan penutup tertutup",
            .lidWarnText: "Selama sesi Claude Code atau aplikasi yang diawasi berjalan, Mac yang tertutup tidak akan tidur.\n\nLaptop tertutup yang terus bekerja menjadi panas: jangan masukkan ke tas atau di bawah bantal. Baterai terkuras seperti saat penutup terbuka.\n\nSaat diaktifkan, pembantu sistem kecil dipasang dan kata sandi administrator diminta sekali.",
            .enable: "Aktifkan",
            .cancel: "Batal",
            .lidFailed: "Pembantu tidak dapat dipasang. Mode tetap nonaktif.",
            .watchAgents: "Awasi agen",
            .agentsHint: "Agen terdeteksi otomatis; hapus centang yang tidak diinginkan",
            .terminals: "Selama terminal terbuka",
            .terminalName: "Terminal",
            .support: "Dukung Veglia ♥",
        ],
        "vi": [
            .watchApps: "Theo dõi ứng dụng",
            .watchHint: "Khi ứng dụng được đánh dấu đang chạy, máy Mac sẽ không ngủ",
            .alwaysOn: "Luôn giữ thức",
            .keepDisplay: "Giữ màn hình sáng",
            .launchAtLogin: "Mở khi đăng nhập",
            .quit: "Thoát Veglia",
            .idle: "Không có gì đang chạy — máy Mac có thể ngủ",
            .manual: "Máy Mac đang thức (bật thủ công)",
            .runningOne: "%@ đang chạy — máy Mac đang thức",
            .runningMany: "%@ đang chạy — máy Mac đang thức",
            .minutes: "%d phút",
            .closed: "(đã đóng)",
            .tipOn: "Veglia: máy Mac sẽ không ngủ",
            .tipOff: "Veglia: đang nghỉ",
            .language: "Ngôn ngữ",
            .systemLanguage: "Theo hệ thống",
            .lidMode: "Làm việc khi đóng nắp",
            .lidWarnTitle: "Máy Mac sẽ tiếp tục làm việc khi đóng nắp",
            .lidWarnText: "Khi phiên Claude Code hoặc ứng dụng được theo dõi đang chạy, máy Mac đóng nắp sẽ không ngủ.\n\nLaptop đóng nắp mà vẫn làm việc sẽ nóng lên: đừng bỏ vào túi hay dưới gối. Pin hao như khi mở nắp.\n\nKhi bật sẽ cài một trợ giúp hệ thống nhỏ và hỏi mật khẩu quản trị một lần.",
            .enable: "Bật",
            .cancel: "Hủy",
            .lidFailed: "Không thể cài trợ giúp. Chế độ vẫn tắt.",
            .watchAgents: "Theo dõi tác nhân",
            .agentsHint: "Tác nhân được tự động phát hiện; bỏ chọn những gì bạn không cần",
            .terminals: "Khi terminal đang mở",
            .terminalName: "Terminal",
            .support: "Ủng hộ Veglia ♥",
        ],
        "th": [
            .watchApps: "เฝ้าดูแอป",
            .watchHint: "ตราบใดที่แอปที่เลือกยังทำงานอยู่ Mac จะไม่หลับ",
            .alwaysOn: "ตื่นอยู่เสมอ",
            .keepDisplay: "เปิดหน้าจอค้างไว้",
            .launchAtLogin: "เปิดเมื่อเข้าสู่ระบบ",
            .quit: "ออกจาก Veglia",
            .idle: "ไม่มีอะไรทำงาน — Mac หลับได้",
            .manual: "Mac ตื่นอยู่ (เปิดเอง)",
            .runningOne: "%@ กำลังทำงาน — Mac ตื่นอยู่",
            .runningMany: "%@ กำลังทำงาน — Mac ตื่นอยู่",
            .minutes: "%d นาที",
            .closed: "(ปิดแล้ว)",
            .tipOn: "Veglia: Mac จะไม่หลับ",
            .tipOff: "Veglia: กำลังพัก",
            .language: "ภาษา",
            .systemLanguage: "ตามระบบ",
            .lidMode: "ทำงานขณะปิดฝา",
            .lidWarnTitle: "Mac จะทำงานต่อขณะปิดฝา",
            .lidWarnText: "ตราบใดที่เซสชัน Claude Code หรือแอปที่เฝ้าดูยังทำงานอยู่ Mac ที่ปิดฝาจะไม่หลับ\n\nแล็ปท็อปที่ปิดฝาแต่ยังทำงานจะร้อน: อย่าใส่กระเป๋าหรือวางใต้หมอน แบตเตอรี่จะหมดเหมือนเปิดฝา\n\nเมื่อเปิดใช้จะติดตั้งตัวช่วยระบบขนาดเล็กและถามรหัสผ่านผู้ดูแลระบบหนึ่งครั้ง",
            .enable: "เปิด",
            .cancel: "ยกเลิก",
            .lidFailed: "ติดตั้งตัวช่วยไม่ได้ โหมดยังปิดอยู่",
            .watchAgents: "เฝ้าดูเอเจนต์",
            .agentsHint: "เอเจนต์จะถูกตรวจพบอัตโนมัติ เอาเครื่องหมายออกได้ถ้าไม่ต้องการ",
            .terminals: "ตราบใดที่เทอร์มินัลเปิดอยู่",
            .terminalName: "เทอร์มินัล",
            .support: "สนับสนุน Veglia ♥",
        ],
    ]
}
